## Import Libraries for intial Data Understanding

In [23]:
import numpy as np 
import pandas as pd

## Load Dataset

In [24]:
df = pd.read_csv('D:/Smartphone-Price-Prediction-Project/Smartphone-Price-Prediction-Project/data/raw/smartphones - smartphones.csv')

In [25]:
df.head()

,model,price,rating,sim,processor,ram,battery,display,camera,card,os
0,OnePlus 11 5G,"₹54,999",89.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",5000 mAh Battery with 100W Fast Charging,"6.7 inches, 1440 x 3216 px, 120 Hz Display wit...",50 MP + 48 MP + 32 MP Triple Rear & 16 MP Fron...,Memory Card Not Supported,Android v13
1,OnePlus Nord CE 2 Lite 5G,"₹19,989",81.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 695, Octa Core, 2.2 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 33W Fast Charging,"6.59 inches, 1080 x 2412 px, 120 Hz Display wi...",64 MP + 2 MP + 2 MP Triple Rear & 16 MP Front ...,"Memory Card (Hybrid), upto 1 TB",Android v12
2,Samsung Galaxy A14 5G,"₹16,499",75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Exynos 1330, Octa Core, 2.4 GHz Processor","4 GB RAM, 64 GB inbuilt",5000 mAh Battery with 15W Fast Charging,"6.6 inches, 1080 x 2408 px, 90 Hz Display with...",50 MP + 2 MP + 2 MP Triple Rear & 13 MP Front ...,"Memory Card Supported, upto 1 TB",Android v13
3,Motorola Moto G62 5G,"₹14,999",81.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 695, Octa Core, 2.2 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with Fast Charging,"6.55 inches, 1080 x 2400 px, 120 Hz Display wi...",50 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...,"Memory Card (Hybrid), upto 1 TB",Android v12
4,Realme 10 Pro Plus,"₹24,999",82.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Dimensity 1080, Octa Core, 2.6 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 67W Fast Charging,"6.7 inches, 1080 x 2412 px, 120 Hz Display wit...",108 MP + 8 MP + 2 MP Triple Rear & 16 MP Front...,Memory Card Not Supported,Android v13

In [26]:
df.shape

(1020, 11)

In [27]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 11 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   model      1020 non-null   str
 1   price      1020 non-null   str
 2   rating     879 non-null    float64
 3   sim        1020 non-null   str
 4   processor  1020 non-null   str
 5   ram        1020 non-null   str
 6   battery    1020 non-null   str
 7   display    1020 non-null   str
 8   camera     1019 non-null   str
 9   card       1013 non-null   str
 10  os         1003 non-null   str
dtypes: float64(1), str(10)
memory usage: 408.8 KB

In [28]:
df.describe()

           rating
count  879.000000
mean    78.258248
std      7.402854
min     60.000000
25%     74.000000
50%     80.000000
75%     84.000000
max     89.000000

In [29]:
df.isnull().sum()

model          0
price          0
rating       141
sim            0
processor      0
ram            0
battery        0
display        0
camera         1
card           7
os            17
dtype: int64

In [30]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df['price'].describe()

count        1020
unique        412
top       ₹14,999
freq           21
Name: price, dtype: object

In [ ]:
df['model'].describe()

count              1020
unique             1020
top       OnePlus 11 5G
freq                  1
Name: model, dtype: object

In [33]:
df.columns

Index(['model', 'price', 'rating', 'sim', 'processor', 'ram', 'battery',
       'display', 'camera', 'card', 'os'],
      dtype='str')

In [34]:
df.describe(include='object')

C:\Users\sachi\AppData\Local\Temp\ipykernel_20376\87514550.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.describe(include='object')

,model,price,sim,processor,ram,battery,display,camera,card,os
count,1020,1020,1020,1020,1020,1020,1020,1019,1013,1003
unique,1020,412,28,298,58,256,369,285,63,48
top,OnePlus 11 5G,"₹14,999","Dual Sim, 3G, 4G, VoLTE, Wi-Fi","Dimensity 700 5G, Octa Core, 2.2 GHz Processor","8 GB RAM, 128 GB inbuilt",5000 mAh Battery with 33W Fast Charging,"6.67 inches, 1080 x 2400 px, 120 Hz Display wi...",50 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...,"Memory Card Supported, upto 1 TB",Android v12
freq,1,21,324,29,267,103,54,40,171,287

In [35]:
df['os'].value_counts()

os
Android v12                           287
Android v11                           233
No FM Radio                           192
Android v10                            58
Android v13                            45
Bluetooth                              38
Android v9.0 (Pie)                     27
Android v10.0                          22
iOS v16                                14
iOS v15                                10
Android v8.1 (Oreo)                    10
Memory Card Not Supported               6
Android v11.0                           4
Android v8.0 (Oreo)                     4
Browser                                 4
iOS v13                                 3
iOS v15.0                               3
Memory Card Supported, upto 32 GB       3
Android v6.0 (Marshmallow)              3
Memory Card Supported, upto 256 GB      2
Android v5.1.1 (Lollipop)               2
Memory Card Supported, upto 64 GB       2
Memory Card (Hybrid), upto 2 TB         2
RTOS (Series 30+)                       2
Harmony v2.0                            2
Memory Card (Hybrid), upto 256 GB       2
EMUI v12                                2
HarmonyOS v2                            1
iOS v13.0                               1
Android v12.1                           1
iOS v12.3                               1
Memory Card Supported                   1
0.3 MP Rear Camera                      1
KAI OS                                  1
iOS v17                                 1
Android v4.4.2 (KitKat)                 1
Android v5.1 (Lollipop)                 1
Hongmeng OS v3.0                        1
Pragati OS (Powered by Android)         1
Memory Card Supported, upto 16 GB       1
Memory Card (Hybrid)                    1
Hongmeng OS v4.0                        1
HarmonyOS v2.0                          1
Memory Card Supported, upto 128 GB      1
Android v7.1 (Nougat)                   1
Android                                 1
Android v9 (Pie)                        1
1.3 MP Rear Camera                      1
Name: count, dtype: int64

In [36]:
df['ram'].unique()

<ArrowStringArray>
[       '12 GB RAM, 256 GB inbuilt',         '6 GB RAM, 128 GB inbuilt',
          '4 GB RAM, 64 GB inbuilt',         '8 GB RAM, 256 GB inbuilt',
         '8 GB RAM, 128 GB inbuilt',         '4 GB RAM, 128 GB inbuilt',
          '3 GB RAM, 32 GB inbuilt',        '16 GB RAM, 256 GB inbuilt',
          '6 GB RAM, 64 GB inbuilt',          '4 GB RAM, 32 GB inbuilt',
          '3 GB RAM, 64 GB inbuilt',          '2 GB RAM, 32 GB inbuilt',
        '16 GB RAM, 512 GB inbuilt',          '2 GB RAM, 64 GB inbuilt',
         '4 GB RAM, 512 MB inbuilt',         '6 GB RAM, 256 GB inbuilt',
        '12 GB RAM, 128 GB inbuilt',         '512 MB RAM, 4 GB inbuilt',
        '18 GB RAM, 512 GB inbuilt',           '6 GB RAM, 1 TB inbuilt',
        '12 GB RAM, 512 GB inbuilt',         '4 GB RAM, 256 GB inbuilt',
                      'Unisoc T107',          '1 GB RAM, 16 GB inbuilt',
        '18 GB RAM, 256 GB inbuilt',                    '64 GB inbuilt',
        '128 MB RAM, 48 MB inbuilt',                   '512 GB inbuilt',
   'Single Core, 208 MHz Processor',        '64 MB RAM, 128 MB inbuilt',
                             'T117',           '4 MB RAM, 4 MB inbuilt',
          '3 GB RAM, 16 GB inbuilt',           '1 GB RAM, 8 GB inbuilt',
                 '1325 mAh Battery',     'Dual Core, 500 MHz Processor',
         '6 GB RAM, 512 GB inbuilt',                  '800 mAh Battery',
 '3.6 inches, 240 x 320 px Display',                 '1750 mAh Battery',
                  '200 mAh Battery',                 '1200 mAh Battery',
          '8 MB RAM, 16 MB inbuilt', '1.5 inches, 120 x 120 px Display',
         '8 GB RAM, 512 GB inbuilt',          '2 GB RAM, 16 GB inbuilt',
 '2.4 inches, 240 x 320 px Display',  '4 inches, 640 x 1136 px Display',
                 '1000 mAh Battery',         '32 MB RAM, 32 MB inbuilt',
         '4 GB RAM, 512 GB inbuilt',                 '1470 mAh Battery',
         '48 MB RAM, 48 MB inbuilt',                     '4 MB inbuilt',
                 '1800 mAh Battery',         '16 MB RAM, 16 MB inbuilt',
          '12 GB RAM, 1 TB inbuilt',                          'No Wifi']
Length: 58, dtype: str