In [2]:
import numpy as np 
import pandas as pd

In [3]:
df = pd.read_csv('D:/Smartphone-Price-Prediction-Project/Smartphone-Price-Prediction-Project/data/raw/smartphones - smartphones.csv')

In [4]:
df.head()

,model,price,rating,sim,processor,ram,battery,display,camera,card,os
0,OnePlus 11 5G,"₹54,999",89.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",5000 mAh Battery with 100W Fast Charging,"6.7 inches, 1440 x 3216 px, 120 Hz Display wit...",50 MP + 48 MP + 32 MP Triple Rear & 16 MP Fron...,Memory Card Not Supported,Android v13
1,OnePlus Nord CE 2 Lite 5G,"₹19,989",81.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 695, Octa Core, 2.2 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 33W Fast Charging,"6.59 inches, 1080 x 2412 px, 120 Hz Display wi...",64 MP + 2 MP + 2 MP Triple Rear & 16 MP Front ...,"Memory Card (Hybrid), upto 1 TB",Android v12
2,Samsung Galaxy A14 5G,"₹16,499",75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Exynos 1330, Octa Core, 2.4 GHz Processor","4 GB RAM, 64 GB inbuilt",5000 mAh Battery with 15W Fast Charging,"6.6 inches, 1080 x 2408 px, 90 Hz Display with...",50 MP + 2 MP + 2 MP Triple Rear & 13 MP Front ...,"Memory Card Supported, upto 1 TB",Android v13
3,Motorola Moto G62 5G,"₹14,999",81.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 695, Octa Core, 2.2 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with Fast Charging,"6.55 inches, 1080 x 2400 px, 120 Hz Display wi...",50 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...,"Memory Card (Hybrid), upto 1 TB",Android v12
4,Realme 10 Pro Plus,"₹24,999",82.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Dimensity 1080, Octa Core, 2.6 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 67W Fast Charging,"6.7 inches, 1080 x 2412 px, 120 Hz Display wit...",108 MP + 8 MP + 2 MP Triple Rear & 16 MP Front...,Memory Card Not Supported,Android v13

In [5]:
# Check initial data types and non-null counts
print(df.info())
print('Missing values: ', df.isnull().sum())

<class 'pandas.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 11 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   model      1020 non-null   str
 1   price      1020 non-null   str
 2   rating     879 non-null    float64
 3   sim        1020 non-null   str
 4   processor  1020 non-null   str
 5   ram        1020 non-null   str
 6   battery    1020 non-null   str
 7   display    1020 non-null   str
 8   camera     1019 non-null   str
 9   card       1013 non-null   str
 10  os         1003 non-null   str
dtypes: float64(1), str(10)
memory usage: 408.8 KB
None
Missing values:  model          0
price          0
rating       141
sim            0
processor      0
ram            0
battery        0
display        0
camera         1
card           7
os            17
dtype: int64

In [6]:
df['model'].sample(10)

395    Realme 9 Pro 5G (8GB RAM + 128GB)
832        Xiaomi Redmi 10 Prime Plus 5G
982                      Realme Narzo 20
390        Realme 8 5G (8GB RAM + 128GB)
815             Xiaomi Redmi 13 Prime 5G
399                             itel P36
903             Motorola Moto G40 Fusion
200                            OPPO A77s
328             Samsung Galaxy S21 Ultra
379                       Realme GT 2 5G
Name: model, dtype: str

In [7]:
def clean_model(x):
    """Clean the phone model name by removing tags like 4G, 5G, and Dual Sim."""
    
    x = x.split("(")[0]
    
    x = x.replace("5G", "").replace("4G", "").replace("Dual Sim", "")
    
    words = x.strip().split()
    if len(words) > 0 and len(words[-1]) == 4 and words[-1].isdigit():
        words.pop()
        
    return " ".join(words).strip()

df["Model"] = df["model"].apply(clean_model)

In [8]:
df['Model'].sample(10)

103                Realme 10s
1006              Oukitel WP9
881                 Nokia 110
300                 Vivo Y01A
897            Tecno Spark 8T
526           Realme GT 2 Pro
256     Samsung Galaxy S22 FE
869        Samsung Galaxy A40
673        Samsung Galaxy A12
769               Vivo X Note
Name: Model, dtype: str

In [9]:
# Dropping the model column 
df.drop('model', axis=1, inplace=True)

In [10]:
df['price'].sample(10)

413       ₹7,249
152    ₹1,42,990
340      ₹14,590
217       ₹9,999
491      ₹23,999
807      ₹11,999
3        ₹14,999
39       ₹28,499
475      ₹39,990
323      ₹84,999
Name: price, dtype: str

In [11]:
def clean_price(x):
  """Clean the price of phone by replacing '₹'."""
  x = x.strip().replace("₹", "").replace(",", "")
  return x

df['Price'] = df['price'].apply(clean_price)

In [12]:
# Dropping price column 
df.drop('price', axis=1, inplace=True)

In [13]:
# change the data type of Price column to float64
df['Price'] = df["Price"].astype('float64')

In [14]:
df['Price'].dtypes

dtype('float64')

In [15]:
df['sim'].sample(10)

545              Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC
229              Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC
309                       Dual Sim, 3G, 4G, VoLTE, Wi-Fi
121              Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC
403                       Dual Sim, 3G, 4G, VoLTE, Wi-Fi
290              Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC
792                       Dual Sim, 3G, 4G, VoLTE, Wi-Fi
951    Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...
241                       Dual Sim, 3G, 4G, VoLTE, Wi-Fi
954              Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC
Name: sim, dtype: str

In [16]:
def clean_sim_ds(x):
  """Cleans the sim of phone into Dual and Single"""
  if "Dual" in x:
    return 1
  elif "Single" in x:
    return 0
  else:
    return np.nan
  
df["Sim"] = df["sim"].apply(clean_sim_ds)

In [17]:
# 5G column - yes or no
def clean_sim_5G(x):
  """Clean the sim column into 5G - Yes or No"""
  if "5G" in x:
    return 1
  else:
    return 0

df['5G'] = df['sim'].apply(clean_sim_5G)

In [18]:
df['5G'].dtypes

dtype('int64')

In [19]:
def clean_sim_irb(x):
  """Cleans the sim into IR column - Yes and No"""
  if "IR" in x:
    return 1
  else:
    return 0
  
df['IrBlaster'] = df["sim"].apply(clean_sim_irb)

In [20]:
def clean_sim_nfc(x):
  """Cleans the sim column into NFC column - Yes and No"""
  if "NFC" in x:
    return 1
  else:
    return 0
df["NFC"] = df["sim"].apply(clean_sim_nfc)

In [21]:
# drop sim column 
df.drop('sim', axis=1, inplace=True)

In [22]:
def clean_processor_speed(x):
  """Extract the numeric processor speed (GHz) from the processor string."""
  if "GHz" in x:
    return x.strip().split(",")[-1].strip().split(" ")[0].replace("GHz", "")
  else:
    return np.nan
  
df['Speed'] = df['processor'].apply(clean_processor_speed)

In [23]:
# change the datatype of Speed column to float
df["Speed"] = df["Speed"].astype("float64")

In [177]:
df['Speed']

0       3.20
1       2.20
2       2.40
3       2.20
4       2.60
        ...
1015    3.00
1016    2.20
1017    2.85
1018    2.20
1019     NaN
Name: Speed, Length: 1020, dtype: float64

In [24]:
def clean_processor_core(x):
  """Extract the core count (e.g., Octa, Quad) from the processor string."""

  if "Core" in x:
      x = x.strip().split(",")
      c = " ".join(x).strip().split(" ")
      if "Core" in c:
        index = c.index("Core")
        return c[index - 1]
      else:
        return np.nan
  else:
      return np.nan

df["Core"] = df["processor"].apply(clean_processor_core)

In [25]:
df['Core'].unique()

<ArrowStringArray>
['Octa', 'Hexa', 'Quad', nan, 'Dual', 'Single']
Length: 6, dtype: str

In [26]:
# map the Core column as per the unique values
core_map = {
    'Octa': 8,
    'Hexa': 6,
    'Quad': 4,
    'Dual': 2,
    'Single': 1
}

df['Core'] = df['Core'].map(core_map)

In [176]:
df['Core']

0       8.0
1       8.0
2       8.0
3       8.0
4       8.0
       ...
1015    8.0
1016    8.0
1017    8.0
1018    8.0
1019    8.0
Name: Core, Length: 1020, dtype: float64

In [27]:
def clean_processor_pn(x):
    """Extract processor brand/series from processor column."""
    
    if pd.isna(x):
        return np.nan

    c = str(x).split(",")[0].strip().lower()

    if "snapdragon" in c or "sanpdragon" in c or "qualcomm" in c:
        return "snapdragon"
    elif "dimensity" in c:
        return "dimensity"
    elif "helio" in c:
        return "helio"
    elif "unisoc" in c or "spreadtrum" in c or "sc9863a" in c or "sc6531e" in c or "tiger" in c:
        return "unisoc"
    elif "exynos" in c or "samsung" in c:
        return "exynos"
    elif "bionic" in c or "a13" in c or "a14" in c or "a15" in c or "a16" in c or "fusion" in c:
        return "bionic"
    elif "google" in c or "tensor" in c:
        return "google"
    elif "kirin" in c:
        return "kirin"
    else:
        return np.nan

df["ProcessorName"] = df["processor"].apply(clean_processor_pn)

In [28]:
df[['processor', 'ProcessorName']].sample(10)

                                           processor ProcessorName
620  Dimensity  810 5G, Octa Core, 2.4 GHz Processor     dimensity
870        Exynos 9820, Octa Core, 2.7 GHz Processor        exynos
266  Dimensity  1200 Max, Octa Core, 3 GHz Processor     dimensity
824            Helio G88, Octa Core, 2 GHz Processor         helio
238    Snapdragon  695, Octa Core, 2.2 GHz Processor    snapdragon
129              Google  Tensor, Octa Core Processor        google
40     Snapdragon  695, Octa Core, 2.2 GHz Processor    snapdragon
110    Dimensity 9000, Octa Core, 3.05 GHz Processor     dimensity
839    Snapdragon 720G, Octa Core, 2.3 GHz Processor    snapdragon
235     Snapdragon 680, Octa Core, 2.4 GHz Processor    snapdragon

In [29]:
# drop the processor column 
df.drop('processor', axis=1, inplace=True)

In [30]:
def clean_ram_ram(x):
    """Normalize RAM to a numeric GB value directly using float."""
    if pd.isna(x):
        return np.nan
    
    x = str(x).strip()
    
    if "GB RAM" in x:
        ram = x.split(",")[0].replace("GB RAM", "").replace("GB", "").strip()
        return float(ram)
            
    elif "MB RAM" in x:
        ram = x.split(",")[0].replace("MB RAM", "").replace("MB", "").strip()
        return round(float(ram) / 1024, 4)

    else:
        return np.nan

df['Ram'] = df['ram'].apply(clean_ram_ram)

In [31]:
df[['ram','Ram']].sample(10)

                           ram  Ram
375   8 GB RAM, 128 GB inbuilt  8.0
330   6 GB RAM, 128 GB inbuilt  6.0
510    3 GB RAM, 32 GB inbuilt  3.0
86    6 GB RAM, 128 GB inbuilt  6.0
649   8 GB RAM, 128 GB inbuilt  8.0
780    2 GB RAM, 32 GB inbuilt  2.0
352    2 GB RAM, 32 GB inbuilt  2.0
648   8 GB RAM, 128 GB inbuilt  8.0
1011  8 GB RAM, 256 GB inbuilt  8.0
996    3 GB RAM, 16 GB inbuilt  3.0

In [32]:
def clean_ram_rom(x):
    """Extract internal storage (ROM) size and normalize to numeric GB."""
    if pd.isna(x):
        return np.nan
    
    x = str(x).strip()

    if "TB inbuilt" in x:
        rom = x.split(",")[-1].replace("TB inbuilt", "").replace("TB", "").strip()
        return float(rom) * 1024

    elif "GB inbuilt" in x:
        rom = x.split(",")[-1].replace("GB inbuilt", "").replace("GB", "").strip()
        return float(rom)

    elif "MB inbuilt" in x:
        rom = x.split(",")[-1].replace("MB inbuilt", "").replace("MB", "").strip()
        return round(float(rom) / 1024, 4)

    return np.nan

df["Rom"] = df["ram"].apply(clean_ram_rom)

In [175]:
df['Rom']

0       256.0
1       128.0
2        64.0
3       128.0
4       128.0
        ...
1015    128.0
1016    128.0
1017    256.0
1018    128.0
1019    128.0
Name: Rom, Length: 1020, dtype: float64

In [ ]:
# drop ram columnn as we extracted the important data/info.
df.drop('ram', axis=1, inplace=True)

In [48]:
def clean_battery_capacity(x):
    """Extract the numeric battery capacity (mAh) from the battery string."""
    if pd.isna(x):
        return np.nan
    
    x = str(x).strip()
    
    if "mAh" in x:
        # Take everything before 'mAh', strip whitespace, and convert to float
        cap = x.split("mAh")[0].strip()
        try:
            return float(cap)
        except ValueError:
            return np.nan
            
    return np.nan

df["Capacity"] = df["battery"].apply(clean_battery_capacity)

In [174]:
df['Capacity']

0       5000.0
1       5000.0
2       5000.0
3       5000.0
4       5000.0
         ...
1015    5000.0
1016    5000.0
1017    5080.0
1018    5000.0
1019    5000.0
Name: Capacity, Length: 1020, dtype: float64

In [55]:
def clean_battery_watt(x):
    """Extract the fast-charging wattage (e.g., 33, 65) from the battery string."""
    if pd.isna(x):
        return np.nan
    
    c = str(x).split()
    
    if "Fast" in c:
        index = c.index("Fast")
        prev_word = c[index - 1]
        
        if prev_word == "with" or not prev_word.endswith("W"): # if the word right before 'Fast' is 'with', wattage wasn't specified
            return np.nan
        
        return float(prev_word.replace("W", "").strip()) # remove 'W' and convert to numeric float
        
    return np.nan

df["Watt"] = df["battery"].apply(clean_battery_watt)

In [173]:
df['Watt']

0       100.0
1        33.0
2        15.0
3         NaN
4        67.0
        ...
1015     68.2
1016     22.5
1017     67.0
1018      NaN
1019      NaN
Name: Watt, Length: 1020, dtype: float64

In [59]:
def clean_battery_fc(x):
  """Categorize whether the phone supports fast charging (Yes/No) ---> (1/0)."""

  if "Fast" in x:
    return 1
  else:
    return 0
  
df["FastCharging"] = df["battery"].apply(clean_battery_fc)

In [172]:
df['FastCharging']

0       1
1       1
2       1
3       1
4       1
       ..
1015    1
1016    1
1017    1
1018    1
1019    1
Name: FastCharging, Length: 1020, dtype: int64

In [65]:
# drop battery column 
df.drop('battery', axis=1, inplace=True)

In [67]:
def clean_display_inches(x):
  """Extract the display size in inches from the screen specification string."""

  if "inches" in x:
    inche = x.strip().split(",")[0].replace("inches", "")
    return float(inche)
  else:
    return np.nan
df["Inches"] = df["display"].apply(clean_display_inches)

In [171]:
df['Inches']

0       6.70
1       6.59
2       6.60
3       6.55
4       6.70
        ...
1015    6.67
1016    6.50
1017    6.60
1018    6.80
1019    6.50
Name: Inches, Length: 1020, dtype: float64

In [86]:
def clean_display_screen_resol(x):
    """Extract the horizontal pixel count (X-axis resolution) from the display string."""
    if pd.isna(x):
        return np.nan
    
    x = str(x).strip()
    
    if "px" in x and "x" in x:  # check if resolution pattern exists (e.g. '1080 x 2400 px')

        res = x.split("px")[0]
        
        if "x" in res:
            x_res = res.split("x")[0].split(",")[-1].strip()
            try:
                return float(x_res)
            except ValueError:
                return np.nan
                
    return np.nan

df["Xaxis"] = df["display"].apply(clean_display_screen_resol)

In [170]:
df['Xaxis']

0       1440.0
1       1080.0
2       1080.0
3       1080.0
4       1080.0
         ...
1015    1080.0
1016     720.0
1017    1080.0
1018    1080.0
1019    1080.0
Name: Xaxis, Length: 1020, dtype: float64

In [93]:
def clean_display_resolu_y(x):
    """Extract the vertical pixel count (Y-axis resolution) from the display string."""
    if pd.isna(x):
        return np.nan
    
    x = str(x).strip()
    
    if "px" in x and "x" in x:
        res = x.split("px")[0]
        
        if "x" in res:
            y_res = res.split("x")[1].strip()
            try:
                return float(y_res)
            except ValueError:
                return np.nan
                
    return np.nan

df["Yaxis"] = df["display"].apply(clean_display_resolu_y)

In [169]:
df['Yaxis']

0       3216.0
1       2412.0
2       2408.0
3       2400.0
4       2412.0
         ...
1015    2460.0
1016    1600.0
1017    2460.0
1018    2400.0
1019    2400.0
Name: Yaxis, Length: 1020, dtype: float64

In [95]:
def clean_display_hz(x):
    """Extract the screen refresh rate (e.g., 60, 90, 120) in Hz from the display string."""
    if pd.isna(x):
        return np.nan
    
    c = str(x).replace(",", " ").split()
    
    if "Hz" in c:
        index = c.index("Hz")
        try:
            return float(c[index - 1])
        except ValueError:
            return np.nan
        
    return np.nan

df["Hz"] = df["display"].apply(clean_display_hz)

In [102]:
df['Hz'].dtypes

dtype('float64')

In [108]:
def clean_display_notches(x):
    """Identify the notch type from the display string."""
    if pd.isna(x):
        return np.nan
    
    x = str(x).lower()
    
    if "dual punch hole" in x:
        return "Dual Punch Hole"
    elif "punch hole" in x:
        return "Punch Hole"
    elif "water drop" in x or "waterdrop" in x:
        return "Water Drop Notch"
    elif "small notch" in x:
        return "Small Notch"
    elif "large notch" in x:
        return "Large Notch"
    elif "notch" in x:
        return "Notch"
    
    return np.nan

df["Notches"] = df["display"].apply(clean_display_notches)

In [110]:
df['Notches'].isnull().sum()

np.int64(135)

In [ ]:
# Drop 'display' column
df.drop('display',axis=1,inplace=True)

In [124]:
def clean_primary_rear_mp(x):
    """Extract the main/first rear camera megapixel value."""
    if pd.isna(x):
        return np.nan
    
    x = str(x).strip()
    
    if "No Rear Camera" in x:
        return 0.0
    
    if "MP" in x:
        val = x.split("MP")[0].strip()
        val = val.split("+")[0].strip() # Handle cases like '50 MP + 8 MP' -> val is '50'
        try:
            return float(val)
        except ValueError:
            return np.nan
            
    return np.nan

df["RearMP"] = df["camera"].apply(clean_primary_rear_mp)

In [132]:
df['RearMP'].dtypes

dtype('float64')

In [129]:
def clean_front_mp(x):
    """Extract the front camera megapixel value."""
    if pd.isna(x):
        return np.nan
    
    x = str(x).strip()
    
    if "Front Camera" in x and "&" in x:
        front = x.split("&")[1].split("MP")[0].strip()
        try:
            return float(front)
        except ValueError:
            return np.nan
            
    elif "No Front Camera" in x or "Rear Camera" in x:
        return 0.0
        
    return np.nan

df["FrontMP"] = df["camera"].apply(clean_front_mp)

In [133]:
df['FrontMP'].dtypes

dtype('float64')

In [134]:
def clean_rear_camera_count(x):
    """Extract the number of rear camera lenses."""
    if pd.isna(x):
        return np.nan
    
    x = str(x).lower()
    
    if "no rear camera" in x:
        return 0
    elif "quad" in x:
        return 4
    elif "triple" in x:
        return 3
    elif "dual" in x:
        return 2
    elif "rear camera" in x or "mp" in x:
        return 1
        
    return np.nan

df["RearCameraCount"] = df["camera"].apply(clean_rear_camera_count)

In [137]:
df[['RearCameraCount','camera']].sample(12)

     RearCameraCount                                             camera
479              1.0                     13 MP Rear & 5 MP Front Camera
9                3.0  50 MP + 8 MP + 2 MP Triple Rear & 32 MP Front ...
672              3.0  50 MP + 2 MP + 2 MP Triple Rear & 8 MP Front C...
743              3.0  48 MP + 2 MP + 2 MP Triple Rear & 8 MP Front C...
170              2.0  8 MP + Depth Sensor Dual Rear & 5 MP Front Camera
317              2.0         50 MP + 2 MP Dual Rear & 5 MP Front Camera
348              3.0  50.3 MP + 50 MP + 12 MP Triple Rear & 32 MP Fr...
779              2.0         13 MP + 2 MP Dual Rear & 8 MP Front Camera
732              4.0               50 MP Quad Rear & 32 MP Front Camera
903              3.0  64 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...
321              2.0                     Foldable Display, Dual Display
429              4.0              108 MP Quad Rear & 32 MP Front Camera

In [140]:
df.drop('camera',axis=1,inplace=True)

In [142]:
def clean_card_support(x):
    """Return 1 for supported, 0 for not supported, and np.nan for missing/shifted data."""
    if pd.isna(x):
        return np.nan
    
    x = str(x)
    
    if "Memory Card" not in x and "card" not in x.lower():
        return np.nan
    
    if "Not Supported" in x or "No" in x:
        return 0
    
    elif "Supported" in x or "Hybrid" in x:
        return 1
        
    return np.nan

df["HasMemoryCard"] = df["card"].apply(clean_card_support)

In [144]:
df['HasMemoryCard'].dtypes

dtype('float64')

In [145]:
def clean_card_hybrid(x):
    """Flag whether the memory card slot is a Hybrid slot (1 = Yes, 0 = Dedicated/No, NaN = Missing/Shifted)."""
    if pd.isna(x):
        return np.nan
    
    x = str(x)
    
    if "Memory Card" not in x and "card" not in x.lower():
        return np.nan
    
    if "Hybrid" in x:
        return 1
    else:
        return 0

df["IsHybrid"] = df["card"].apply(clean_card_hybrid)

In [149]:
df['IsHybrid'].isnull().sum()

np.int64(279)

In [150]:
def clean_card_extrasupport(x):
    """Extract expandable storage capacity in GB (e.g., 512, 1024, 0)."""
    if pd.isna(x):
        return np.nan
    
    x = str(x).strip()
    
    if "Not Supported" in x:
        return 0.0
    
    if "upto" in x:
        cap = x.split("upto")[-1].strip()
        
        if "TB" in cap:
            val = cap.replace("TB", "").strip()
            try:
                return float(val) * 1024
            except ValueError:
                return np.nan
                
        elif "GB" in cap:
            val = cap.replace("GB", "").strip()
            try:
                return float(val)
            except ValueError:
                return np.nan
                
    return np.nan

df["ExtraSupport"] = df["card"].apply(clean_card_extrasupport)

In [153]:
df['ExtraSupport']

0          0.0
1       1024.0
2       1024.0
3       1024.0
4          0.0
         ...
1015       NaN
1016    1024.0
1017       0.0
1018    1024.0
1019    1024.0
Name: ExtraSupport, Length: 1020, dtype: float64

In [ ]:
# drop 'card' column
df.drop('card',axis=1,inplace=True)

In [157]:
df['os'].sample(10)

472           Android v11
262           Android v10
523           Android v12
828           Android v12
80            Android v12
846             Bluetooth
372           Android v10
870    Android v9.0 (Pie)
349           Android v13
246           Android v12
Name: os, dtype: str

In [158]:
def clean_os(x):
    """Extract operating system family from the OS column."""
    if pd.isna(x):
        return np.nan
    
    x = str(x).lower()
    
    if "android" in x or "emui" in x or "pragati" in x or "miui" in x or "oxygenos" in x:
        return "android"
    elif "ios" in x:
        return "ios"
    elif "harmonyos" in x or "hongmeng" in x:
        return "harmonyos"
    elif "kaios" in x:
        return "kaios"
    elif "rtos" in x or "symbian" in x or "java" in x:
        return "other"
    else:
        return np.nan

df["OS"] = df["os"].apply(clean_os)

In [163]:
df['OS']

0       android
1       android
2       android
3       android
4       android
         ...
1015        NaN
1016    android
1017    android
1018    android
1019    android
Name: OS, Length: 1020, dtype: str

In [ ]:
# drop 'os' column
df.drop('os', axis=1, inplace=True)

In [166]:
df.head()

,rating,Model,Price,Sim,5G,IrBlaster,NFC,Speed,Core,ProcessorName,...,Hz,Notches,RearCamera,RearMP,FrontMP,RearCameraCount,HasMemoryCard,IsHybrid,ExtraSupport,OS
0,89.0,OnePlus 11,54999.0,1.0,1,0,1,3.2,8.0,snapdragon,...,120.0,Punch Hole,1.0,50.0,16.0,3.0,0.0,0.0,0.0,android
1,81.0,OnePlus Nord CE 2 Lite,19989.0,1.0,1,0,0,2.2,8.0,snapdragon,...,120.0,Punch Hole,1.0,64.0,16.0,3.0,1.0,1.0,1024.0,android
2,75.0,Samsung Galaxy A14,16499.0,1.0,1,0,0,2.4,8.0,exynos,...,90.0,Water Drop Notch,1.0,50.0,13.0,3.0,1.0,0.0,1024.0,android
3,81.0,Motorola Moto G62,14999.0,1.0,1,0,0,2.2,8.0,snapdragon,...,120.0,Punch Hole,1.0,50.0,16.0,3.0,1.0,1.0,1024.0,android
4,82.0,Realme 10 Pro Plus,24999.0,1.0,1,0,0,2.6,8.0,dimensity,...,120.0,Punch Hole,1.0,108.0,16.0,3.0,0.0,0.0,0.0,android

In [167]:
df.columns

Index(['rating', 'Model', 'Price', 'Sim', '5G', 'IrBlaster', 'NFC', 'Speed',
       'Core', 'ProcessorName', 'Ram', 'Rom', 'Capacity', 'Watt',
       'FastCharging', 'Inches', 'Xaxis', 'Yaxis', 'Hz', 'Notches',
       'RearCamera', 'RearMP', 'FrontMP', 'RearCameraCount', 'HasMemoryCard',
       'IsHybrid', 'ExtraSupport', 'OS'],
      dtype='str')

In [168]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 28 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   rating           879 non-null    float64
 1   Model            1020 non-null   str
 2   Price            1020 non-null   float64
 3   Sim              1019 non-null   float64
 4   5G               1020 non-null   int64
 5   IrBlaster        1020 non-null   int64
 6   NFC              1020 non-null   int64
 7   Speed            945 non-null    float64
 8   Core             980 non-null    float64
 9   ProcessorName    967 non-null    str
 10  Ram              993 non-null    float64
 11  Rom              997 non-null    float64
 12  Capacity         987 non-null    float64
 13  Watt             769 non-null    float64
 14  FastCharging     1020 non-null   int64
 15  Inches           987 non-null    float64
 16  Xaxis            987 non-null    float64
 17  Yaxis            987 non-null    float64
 18  Hz               611 non-null    float64
 19  Notches          885 non-null    str
 20  RearCamera       958 non-null    float64
 21  RearMP           958 non-null    float64
 22  FrontMP          958 non-null    float64
 23  RearCameraCount  981 non-null    float64
 24  HasMemoryCard    741 non-null    float64
 25  IsHybrid         741 non-null    float64
 26  ExtraSupport     622 non-null    float64
 27  OS               743 non-null    str
dtypes: float64(20), int64(4), str(4)
memory usage: 261.6 KB

In [179]:
string_cols = df.select_dtypes(include=['object', 'string']).columns
print(string_cols)

Index(['Model', 'ProcessorName', 'Notches', 'OS'], dtype='str')

In [ ]:
# Converting text columns to lowercase
for col in string_cols:
    df[col] = df[col].str.strip().str.lower()
    df[col] = df[col].replace({'nan': np.nan, 'none': np.nan})

In [191]:
df[['Model', 'ProcessorName', 'Notches', 'OS']].sample(10)

                        Model ProcessorName           Notches       OS
466            nokia g11 plus        unisoc  water drop notch  android
302                realme c30        unisoc  water drop notch  android
932            eunity u1 livo           NaN               NaN      NaN
57      xiaomi redmi note 10s         helio        punch hole  android
44                   vivo y35    snapdragon  water drop notch  android
364  samsung galaxy s24 ultra    snapdragon        punch hole  android
984                realme c11         helio  water drop notch  android
246             oppo f21s pro    snapdragon        punch hole  android
574                  vivo y71    snapdragon               NaN  android
136           apple iphone 11        bionic       large notch      ios

In [192]:
df

,rating,Model,Price,Sim,5G,IrBlaster,NFC,Speed,Core,ProcessorName,...,Hz,Notches,RearCamera,RearMP,FrontMP,RearCameraCount,HasMemoryCard,IsHybrid,ExtraSupport,OS
0,89.0,oneplus 11,54999.0,1.0,1,0,1,3.20,8.0,snapdragon,...,120.0,punch hole,1.0,50.0,16.0,3.0,0.0,0.0,0.0,android
1,81.0,oneplus nord ce 2 lite,19989.0,1.0,1,0,0,2.20,8.0,snapdragon,...,120.0,punch hole,1.0,64.0,16.0,3.0,1.0,1.0,1024.0,android
2,75.0,samsung galaxy a14,16499.0,1.0,1,0,0,2.40,8.0,exynos,...,90.0,water drop notch,1.0,50.0,13.0,3.0,1.0,0.0,1024.0,android
3,81.0,motorola moto g62,14999.0,1.0,1,0,0,2.20,8.0,snapdragon,...,120.0,punch hole,1.0,50.0,16.0,3.0,1.0,1.0,1024.0,android
4,82.0,realme 10 pro plus,24999.0,1.0,1,0,0,2.60,8.0,dimensity,...,120.0,punch hole,1.0,108.0,16.0,3.0,0.0,0.0,0.0,android
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1015,83.0,motorola moto edge s30 pro,34990.0,1.0,1,0,0,3.00,8.0,snapdragon,...,120.0,punch hole,1.0,64.0,16.0,3.0,NaN,NaN,NaN,NaN
1016,75.0,honor x8,14990.0,1.0,1,0,0,2.20,8.0,snapdragon,...,NaN,water drop notch,1.0,48.0,8.0,3.0,1.0,0.0,1024.0,android
1017,85.0,poco x4 gt,28990.0,1.0,1,1,1,2.85,8.0,dimensity,...,144.0,punch hole,1.0,64.0,16.0,3.0,0.0,0.0,0.0,android
1018,80.0,motorola moto g91,19990.0,1.0,1,0,1,2.20,8.0,snapdragon,...,NaN,punch hole,1.0,108.0,32.0,3.0,1.0,0.0,1024.0,android
1019,74.0,samsung galaxy m52s,24990.0,1.0,1,0,0,NaN,8.0,NaN,...,NaN,water drop notch,1.0,64.0,32.0,3.0,1.0,0.0,1024.0,android

In [ ]:
# save the final cleaned dataset
df.to_csv("D:/Smartphone-Price-Prediction-Project/Smartphone-Price-Prediction-Project/data/processed/cleaned_smartphones.csv", index=False)